sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
services:
  - rabbitmq
env:
  matrix:
    - DJANGO_VERSION="Django>=1.8,<1.9"
    - DJANGO_VERSION="Django>=1.9,<1.10"
    - DJANGO_VERSION="Django>=1.10,<1.11"
cache:
  directories:
  - $HOME/.cache/pip/wheels
install:
  - pip install -U pip wheel
  - pip install -r requirements/qa.txt
  - pip install -r requirements/ci.txt
  - pip install "${DJANGO_VERSION}"
  - pip install .
script:
  - coverage run -m pytest -v -s
after_success:
  - codecov
