language: python
services:
  - rabbitmq
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django110
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.4
      env: TOXENV=py34-django110
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django110
cache:
  directories:
  - $HOME/.cache/pip/wheels
install:
  - pip install -U pip wheel
  - pip install .
  - pip install -r requirements/qa.txt
  - pip install -r requirements/ci.txt
script:
  - tox
