version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
  py27:
    build:
      context: .
      dockerfile: compose/py27
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py27-django18,py27-django19,py27-django110
    ports:
      - "8000:8000"
  py34:
    build:
      context: .
      dockerfile: compose/py34
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py34-django18,py34-django19,py34-django110
    ports:
      - "8001:8000"
  py35:
    build:
      context: .
      dockerfile: compose/py35
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py35-django18,py35-django19,py35-django110
    ports:
      - "8002:8000"
  kernel:
    build:
      context: .
      dockerfile: compose/kernel
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      PYTHONPATH: /code/.tox3.5.2/py35-django110/lib/python3.5/site-packages
    ports:
      - "8889:8889"
