version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
  py27:
    build:
      context: .
      dockerfile: compose/py27
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py27-django18,py27-django19,py27-django110
      DJANGO_SETTINGS_MODULE: demo.settings
  py34:
    build:
      context: .
      dockerfile: compose/py34
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py34-django18,py34-django19,py34-django110
      DJANGO_SETTINGS_MODULE: demo.settings
  py35:
    build:
      context: .
      dockerfile: compose/py35
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      DJANGO_SETTINGS_MODULE: demo.settings
      TOXENV: py35-django18,py35-django19,py35-django110
