version: '2'
services:
  py27:
    build:
      context: .
      dockerfile: compose/py27
    command: tox
    volumes:
      - .:/code
  py34:
    build:
      context: .
      dockerfile: compose/py34
    command: tox
    volumes:
      - .:/code
  py35:
    build:
      context: .
      dockerfile: compose/py35
    command: tox
    volumes:
      - .:/code
