version: '3'
services:
  rabbitmq:
    image: rabbitmq
  py27: &py27
    image: asgirabbitmq_py27
    volumes:
      - ..:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
  daphne:
    <<: *py27
    container_name: bench2_daphne
    command: /code/.tox2.7.13/py27-django110/bin/daphne testproject.asgi.rabbitmq:channel_layer -e tcp:port=8000:interface=0.0.0.0
  worker:
    <<: *py27
    container_name: bench2_worker
    command: /code/.tox2.7.13/py27-django110/bin/django-admin runworker --settings testproject.settings.channels_rabbitmq
  benchmark:
    <<: *py27
    container_name: bench2_benchmark
    command: /code/.tox2.7.13/py27-django110/bin/python -m benchmark ws://daphne:8000
    depends_on:
      - daphne
      - worker
